$(document).ready(function(){
    $("#inst").click(function(){
     $("#quiz-wrapper").hide();
     $("#popup").show();
    });
    $("#close").click(function(){
      $("#popup").hide();
      $("#quiz-wrapper").show();
    });
  });